debug: true
server:
  session:
    cookie:
      http-only: true
      secure: true
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: gecadmin
    key-store-Type: PKCS12
    key-alias: gecscf
spring:
  application:
    name: ui-service
  thymeleaf:
    cache: false
  jackson:
    time-zone: Asia/Bangkok
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_POST:6379}
security:
  user:
    password: none
scf:
  services:
    api:
      host: localhost
      port: 8443
      context-path: /api
  product:
    version: ${PRODUCT_VERSION:N/a}