debug: true
server:
  port: 433
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: gecadmin
    keyStoreType: PKCS12
    keyAlias: gecscf
spring:
  application:
    name: ui-service
  thymeleaf:
    cache: false
security:
  user:
    password: none