debug: true
server:
  session:
    cookie:
      http-only: true
      secure: true
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: gecadmin
    keyStoreType: PKCS12
    keyAlias: gecscf
spring:
  application:
    name: ui-service
  thymeleaf:
    cache: false
  jackson:
    time-zone: Asia/Bangkok
security:
  user:
    password: none